### ISSUE TITLE
WowUp integration 

### ISSUE THREAD

**Issue by kingreboot** [Numynum/MacroToolkit#1]
Thank you so much for Keeping this addon alive. If you plan to keep working on it, any chance you be willing to set this project up with a release that can work with the WoWup. If you need help figuring out how to set up this project properly to work with wowup, the discord has plenty of people to help https://discord.gg/xFWzURnZ

**Comment by Numynum** [comment]
glad you like it :)
I have no immediate plans to make more changes than those I have made now (all current features seem to be working as expected, for me at least)
if that changes, I might set up github releases

**Comment by kingreboot** [comment]
I thought I saw a comment about cleaning up the addon, it does not fit that well into the window?

**Comment by kingreboot** [comment]
never mind, I miss read the comment about not making it look pretty. Well thanks for making it work in a way that I can use it while I look for other version/someone else takes the project over
