### ISSUE TITLE
Options menu no longer exists

### ISSUE THREAD

**Issue by filliph** [Numynum/MacroToolkit#11]
When pressing the Options button, or when opening the options panel manually, there are no settings for MacroToolkit. It doesn't exist in the AddOns list, and the Options button simply takes you to the last opened options pane, whatever it was.

**Comment by Numynum** [comment]
![image](https://user-images.githubusercontent.com/17293527/203826389-e07f2ecf-18a9-49b2-8e8a-b5b3cf991dad.png)
works fine for me
what game version are you using? and do you have issues when you have no other addons installed?

**Comment by filliph** [comment]
I've had a chance to go through this, and it turns out the options _are_ there, I just expected Macro Toolkit to show in this region:

![image](https://user-images.githubusercontent.com/9424286/203988846-01a7f156-dbbe-42c8-9269-51dc590770ac.png)

Not here:

![image](https://user-images.githubusercontent.com/9424286/203988881-b6480091-f714-45ed-a2db-1afa09313ada.png)

The "options button doesn't take you to the options" issue still exists with only this add-on enabled.

**Comment by Numynum** [comment]
Well, as you can see in both your screenshots, it's already not in alphabetical order :)

the issue with options button not going to the right place is due to a blizzard bug (you can no longer navigate to a subcategory automatically)
I've fixed this, so it'll open the main addon page instead; this will be part of the next update (which isn't out yet, as I'm working on some more improvements too)

Just to be clear, MacroToolkit uses the same, normal, method of adding into the options panel as every other addon; it's just that for some reason, we're the last one adding ourselves to the list :)

**Comment by filliph** [comment]
From what I can tell by the code, the reason why yours shows up below everyone else is because of this line: https://github.com/Numynum/MacroToolkit/blob/master/MacroToolkit/modules/options.lua#L914

Every other add-on (with the exception of TomTom, as you noted) lets AceConfig handle creating the panel. AceConfig does this via `AceConfigDialog:AddToBlizOptions` and you can see it in use here: https://github.com/gOOvER/Name2Chat/blob/6605651de1071b4c97d31234f964813767b9a74b/Name2Chat.lua#L153 - opening to that category can be seen here: https://github.com/gOOvER/Name2Chat/blob/6605651de1071b4c97d31234f964813767b9a74b/Name2Chat.lua#L121

As far as I can tell, there does not appear to be a single reason to create your own main frame other than having a credits splash screen, am I missing something?

**Comment by Numynum** [comment]
TomTom isn't the only exception MikSBT shows up before MethodRT as well for example

I got curious and checked; the reason MT shows last, is that we add ourselves at the end of the loading screen (on `PLAYER_ENTERING_WORLD` to be precise)
most addons do so on `ADDON_LOADED` instead
why? I wasn't the one who initially created this addon (or the options ui for that matter), so frankly I have no idea :p
in the end, using a custom panel, or an aceconfig panel, makes absolutely no difference to the order :)
blizzard just doesn't sort, so it's a matter of who loads first (which is _mostly_ alphabetically)

**Comment by filliph** [comment]
I see, that's fair enough then 😄 Thanks for the info! This also explains why Wowhead Looter is always first 🤔 

The reason why I push(ed) so hard for "fixing the sort" was to avoid other people getting confused like I was, I thought perhaps AceConfig did some kind of sorting internally.

Regardless, having the options button go to the main page is perfect, thanks for the quick fix!

**Comment by Numynum** [comment]
no worries, I get it :)
I might change it, not 100% sure..
honestly, this addon was left in a very chaotic state, after having 4 or 5 different people patching things over the years, and nobody doing cleanup 🙈 which is why I'm mostly trying to focus on the bigger picture issues first 🙂
