### ISSUE TITLE
"dragonflying" is now a valid condition 

### ISSUE THREAD

**Issue by Tovrin** [Numynum/MacroToolkit#14]
I get an error when using the "dragonflying" condition, suggesting using hte "flying" condition instead. It's not a huge issue as the macro still works, but it might be worth updating for the new condition.

**Comment by Numynum** [comment]
Cheers for letting me know, I'll take a look ^^

**Comment by Numynum** [comment]
![image](https://user-images.githubusercontent.com/17293527/208538243-e7c3df09-ad4f-4d7f-8818-fb2458e9f9b0.png)
doesn't seem like "dragonflying" is actually a valid macro condition 🤔

**Comment by Tovrin** [comment]
I should be.  This macro works perfectly

`#showtooltip
/stopcasting
/cast [mounted,dragonflying] Surge Forward; [@focus]
 Misdirection`

**Comment by Numynum** [comment]
Likely because of the `[mounted]` part
try it while on a regular mount, if your macro works, it should cast misdirect; but it'll probably (fail to) cast surge forward
when I tried a macro with that, it didn't work anyways, and the game gave me the error from my screenshot :)

**Comment by Tovrin** [comment]
There's a lot of weird noise on the forums about this condition and I suspect some of it is just plain wrong.  You know this stuff far better and I'd say you're right on this one.

Sorry for the trouble.
