### ISSUE TITLE
Some new Macro commands not recognized

### ISSUE THREAD

**Issue by Falcon2k1** [Numynum/MacroToolkit#15]
The following commands, which appear to have been added recently, do not show up as valid options.

Source: https://worldofwarcraft.com/en-us/news/23874318/updated-nov-15-dragonflight-pre-expansion-phase-2-update-notes-now-live

```
/loadoutname
/lon
/loudoutindex
/loi
/specname
/spn
/specindex
/spi
```

**Comment by Numynum** [comment]
fixed in next update
seems blizzard is using a new way of adding these secure macros 🤷‍♂️
