### ISSUE TITLE
extended macros editing real macro instead of extended script

### ISSUE THREAD

**Issue by kived** [Numynum/MacroToolkit#17]
In the latest update, when editing extended macros the macro text shown is the actual macro to click the buttons instead of the extended script. Downgrading to the previous version fixes the issue.

v10.0.2-6:
![Screenshot_20221226_041652](https://user-images.githubusercontent.com/1126441/209590059-0f769df3-d05e-47db-b9bb-48011d6e8020.png)

v10.0.2-7:
![Screenshot_20221226_041812](https://user-images.githubusercontent.com/1126441/209590061-7b056f0a-c7f2-4a35-9f17-3b2ab0f6e7ce.png)

**Comment by Numynum** [comment]
should be fixed in next update
