### ISSUE TITLE
Wrath classic support

### ISSUE THREAD

**Issue by Galdoring74** [Numynum/MacroToolkit#19]
there is an error on Wrath client that makes MTK not work. Is there anyone working to fix this?

**Comment by Numynum** [comment]
I don't play wrath, and don't plan to support it
if someone else want to put in the work, they're free to create a PR

**Comment by Numynum** [comment]
I have made a small change that seems to fix things for now. If there are more issues, you're free to report them, but my stance on classic support hasn't changed 🙂
