### ISSUE TITLE
Lua error when used with ElvUI

### ISSUE THREAD

**Issue by Konsafloof** [Numynum/MacroToolkit#2]
Addons Enabled,
Macro Toolkit
MacroToolkit Icon Data
ElvUI
ElvUI OptionsUI

I get this lua error when using MacroToolkit and ElvUI at once. Sorry for any inconvenience.

Message: ...erface/AddOns/ElvUI/Core/Modules/ActionBars/Bind.lua:278: Usage: UnregisterEvent(eventname): 'eventname' - string expected.
Time: Sat Oct 29 20:35:43 2022
Count: 1
Stack: ...erface/AddOns/ElvUI/Core/Modules/ActionBars/Bind.lua:278: Usage: UnregisterEvent(eventname): 'eventname' - string expected.
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:153: in function `UnregisterEvent'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/Bind.lua"]:278: in function `ADDON_LOADED'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1575: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1484>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1791: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1806: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1832: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1941: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:226: in function <Interface/AddOns/ElvUI/Core/init.lua:225>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...vUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...vUI/Libraries/Core/Ace/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>

**Comment by Numynum** [comment]
seems to have been an issue in elvui (fixed in https://github.com/tukui-org/ElvUI/commit/8f0283264a6acf6c7d12a506231052a44012b2cb)

**Comment by Konsafloof** [comment]
ah sorry
