### ISSUE TITLE
mainframe.lua:430;484 & MacroToolkit.lua:672

### ISSUE THREAD

**Issue by Fileor** [Numynum/MacroToolkit#20]
[BugReportMacroToolkit.zip](https://github.com/Numynum/MacroToolkit/files/10461220/BugReportMacroToolkit.zip)

Dear Mark @Numynum
Please take a look at the LUA-Errors (code & screenshots) I posted above.
We are pretty screwed without your amazing AddOn (90% of my macros using 700+ characters)!
If you need any further information please let me know.
Big thanks in advance.

    Macro Toolkit v10.0.2-8 (2022-12-27)

**Comment by Numynum** [comment]
Hi, are you playing wrath by any chance?

**Comment by Numynum** [comment]
wrath should be working OK again
I do not play classic however, and the differences between classic and retail have only grown larger, so be aware that if blizzard breaks anything in this addon, it might not get fixed
