### ISSUE TITLE
Macro hotkey works even after uninstalling the addon

### ISSUE THREAD

**Issue by comiluv** [Numynum/MacroToolkit#23]
* Description
Macros that are hotkeys directly assigned with this addon still works by pressing the assigned hotkey even after uninstalling the addon
* Steps to repro
1. Make a macro that does ```/s Macro Toolkit Works```
2. Assign a hotkey for this macro such as ```1```
3. Press ```1``` to confirm this hotkey works
4. Turn of WOW
5. Uninstall the addon by removing \Interface\Addons\MacroToolkit and \MacroToolkitIcons
6. Turn on WOW
7. Press ```1```

**Comment by Numynum** [comment]
are you talking about macros moved to the action bar, or macros created in the `key bind only` tab?
if talking about the first, that's working as intended
if talking about the second, that's not something I can reproduce, and considering the addon has to register those keybind only macros before they work, I don't see how that could even be possible 🙂

**Comment by comiluv** [comment]
I made the keybind using the button highlighted with green marker in the screenshot below
![WoWScrnShot_021323_184609](https://user-images.githubusercontent.com/19642705/218425175-eaab78ad-4c47-46f9-a490-e8d77f210a8b.jpg)

I tested again by
1. Install MacroToolkit
2. Make a macro "/s test hotkey" and assigned it to ```1``` using the highlighted button in the above screenshot
3. Completely turn off World of Warcraft
4. Uninstall MacroToolkit
5. Login World of Warcraft
6. Disable all addons
7. Press ```1```
![WoWScrnShot_021323_185150](https://user-images.githubusercontent.com/19642705/218426174-714376df-f430-4d8c-9f3e-53528eadbf72.jpg)

**Comment by comiluv** [comment]
It's not a major flaw or anything because I play WOW with MacroToolkit installed all the time but it's something I noticed as I go on about enabling/disabling addons

**Comment by Numynum** [comment]
I see, interesting, did not know about that 🙂 (I only started working on/fixing this addon during DF launch)
I don't think I'll change this; although it is a little confusing that you cannot see it in the keybindings list, but blame blizzard for that one I guess ^^

**Comment by Numynum** [comment]
thanks for the screenshot, I didn't even remember/know you could keybind regular macros

**Comment by comiluv** [comment]
Could be considered as a feature :grin:
