### ISSUE TITLE
Toolkit UI will not open in Classic Era

### ISSUE THREAD

**Issue by FadedMazix** [Numynum/MacroToolkit#26]
As the title says. No other addons loaded except for the Hardcore addon, attempted to load the Macro Toolkit UI via / command and through the original macro menu. The / command refuses to go through and the button closes the menu and nothing else appears.

I understand classic support is incidental, but if this could be looked into it would be appreciated.

**Comment by Numynum** [comment]
You can try an old version from curseforge
you'll need to manually download it from the site

**Comment by FadedMazix** [comment]
To anyone in the future having the same issue, use v9.0.1 most recent version that still works with classic era.

**Comment by Numynum** [comment]
the latest version should work again now; since blizzard finally updated classic era
