### ISSUE TITLE
[Request] Allow an option to partition current macro slots similar to MegaMacro

### ISSUE THREAD

**Issue by JoeLatte88** [Numynum/MacroToolkit#28]
Since MegaMacro has largely been left to the wayside since the beginning of Dragonflight, the most important aspect of it for me was the partitioning of the default allocation of the 138 macro slots. 

Example:
Blizzard Default allocation: 
- 120 slots for Global macros
- 18 slots for Character macros

Mega Macro fixed allocation:
- 60 Global macros
- 30 Class macros
- 30 Specialization macros
- 8 Character specific macros
- 10 Character specialization specific macros

Ultimately, I think having the ability to either allow users to partition macros slot allocation or having the slot allocation fixed to at least allow for better organization would be a nice enhancement long term. I personally feel that just being able to partition into class/spec macros is really nice, but hopefully this isn't completely out of scope for the addons future plans :)

I'd understand if this is a bit much though.

**Comment by Numynum** [comment]
I'm not planing on adding any new features as such
this addon is quite low on my priority list, and my time is rather limited sadly 🙂
