### ISSUE TITLE
Invalid argument for mods using multiple modifires

### ISSUE THREAD

**Issue by BadgerMH** [Numynum/MacroToolkit#3]
I've been using macros for as long as I can remember, and I can't really imagine myself playing without them. With the expansion and the new trees and multiple abilities, I've found myself searching for a macro addon that would help me streamline the process and organization of them. I found this gem and am glad it has been updated for DF. Below is probably my main style of macro format to help get the most out of my gaming experience:
(my druid shifting button macro)

#showtooltip
/use [mod:alt:ctrl:shift] Stampeding Roar; [mod:alt:shift] Dash; [mod:ctrl:shift] Darkflight ;[mod:ctrl:alt] Bear Form ;[mod:alt] Travel Form ;[mod:ctrl] Moonkin Form ;[mod:shift] Cat Form; Prowl

One interesting thing I found is the addon flags any mods that go beyond 1 modifier as invalid arguments. Just wanted to pass this along. Thank you again for making the macro life a bit easier!

**Comment by Numynum** [comment]
glad you like it :)
it seems that the validator for mod is indeed wrong, I'll put it on the todo list :)

**Comment by Faadoo** [comment]
Hi
thanks for your work I have been useing your addon for years now. I have like 50 macros with modifiers. non are working. a sample is blew

/maintank player
/run SendChatMessage(SecureCmdOptionParse("[mod:shift]moving follow me -->{RT6} ;[mod:ctrl]{rt6} Stay in Raid {rt6} We move together;[mod:alt]{rt7} Wait Regroup Pause {rt7};always stay close to -->{rt6}"),(UnitIsGroupLeader("player")or UnitIsGroupAssistant("player"))and"RAID_WARNING"or"INSTANCE_CHAT")


it seams to be the same issue as the OP. all my macros are more than 255 chtrs...

**Comment by Numynum** [comment]
hi @Faadoo, the OP is saying that the addon is incorrectly warning him that [mod:shift:alt] is invalid, but it still works
I've tried your example macro on the latest version, and it works for me (on the latest version, v10.0.0-6)🤔 
both with clicking the macro on my action bar, as well as using a keybind on the action bar

**Comment by Faadoo** [comment]
hi
yahh thanks it workd. and today I log back to use it all modifers work normaly but the Shit

**Comment by Numynum** [comment]
@BadgerMH next version should properly parse `mod:shift:alt` etc as valid; and will remove the colon (`:`) characters when shortening the macro
