### ISSUE TITLE
Unable to copy an extended macro from another character

### ISSUE THREAD

**Issue by divinemaiden** [Numynum/MacroToolkit#7]
5x Interface/AddOns/MacroToolkit/modules/copyframe.lua:123: Usage: local success = self:SetFont(fontFile, height, flags)
[string "=[C]"]: in function `SetFont'
[string "@Interface/AddOns/MacroToolkit/modules/copyframe.lua"]:123: in function `CreateCopyFrame'
[string "@Interface/AddOns/MacroToolkit/modules/mainframe.lua"]:513: in function <Interface/AddOns/MacroToolkit/modules/mainframe.lua:512>

Locals:
(*temporary) = MacroToolkitCText {
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 0 = <userdata>
}
(*temporary) = "Fonts\FRIZQT__.TTF"
(*temporary) = 10

**Comment by Numynum** [comment]
fixed in next update

**Comment by Numynum** [comment]
sorry actually no, I only fixed the issue with fonts, there are a few other issues that I'll have to check 🙈

**Comment by Numynum** [comment]
fixed now :)
