### ISSUE TITLE
Macro names overlap

### ISSUE THREAD

**Issue by Imiona** [Numynum/MacroToolkit#8]
The Fonts on the Macros are messed up for me

Vers: 10.0.0 - 9

https://i.imgur.com/VjORHjp.png

**Comment by Numynum** [comment]
![image](https://user-images.githubusercontent.com/17293527/201487235-8692f02a-33cf-4557-919f-6b26c33e739a.png)
https://www.curseforge.com/wow/addons/macro-toolkit
